import { omnichannelDiscoveryAgent } from "./OmnichannelDiscoveryAgent";
import { entityResolutionAgent } from "./EntityResolutionAgent";
import { opportunityAgent } from "./OpportunityAgent";
import { leadGraphEngine } from "./LeadGraphEngine";
import { outreachAgent } from "./OutreachAgent";
import { adsAgent } from "./AdsAgent";
import { CanonicalLead, SupervisorMissionPlan } from "./types";
import { PlatformSource } from "../adapters/types";

export interface SupervisorObjectiveInput {
  objective: string; // e.g. "Find 100 salons in Pune that could benefit from Docodo"
  city?: string;
  industry?: string;
  limit?: number;
  sources?: PlatformSource[];
  autoGenerateDrafts?: boolean;
}

export class GrowthSupervisorAgent {
  private runs: SupervisorMissionPlan[] = [];

  public async executeMission(input: SupervisorObjectiveInput): Promise<SupervisorMissionPlan> {
    const city = input.city || "Pune";
    const industry = input.industry || "salon";
    const limit = input.limit || 25;
    const sources: PlatformSource[] = input.sources || [
      "google_places",
      "website",
      "instagram",
      "facebook",
      "linkedin",
      "x",
      "reddit",
    ];

    const missionId = `mission_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;
    const plan: SupervisorMissionPlan = {
      id: missionId,
      objective: input.objective,
      selectedSources: sources,
      stages: [
        { name: "Omnichannel Discovery", status: "RUNNING", details: "Scanning selected data sources" },
        { name: "Entity Resolution & LeadGraph", status: "PENDING" },
        { name: "Opportunity Mapping & Scoring", status: "PENDING" },
        { name: "CRM Funnel Placement", status: "PENDING" },
        { name: "Personalized Outreach Drafting", status: "PENDING" },
        { name: "Human Approval Gate", status: "PENDING" },
      ],
      budgetAllocated: 1000,
      budgetSpent: 0,
      discoveredLeads: [],
      pendingApprovals: [],
      auditLogs: [],
    };

    const log = (step: string, agent: string, message: string, level: "INFO" | "WARN" | "ERROR" | "GATE" = "INFO") => {
      plan.auditLogs.push({
        timestamp: new Date().toISOString(),
        step,
        agent,
        message,
        level,
      });
    };

    log("Mission Initiation", "GrowthSupervisorAgent", `Started acquisition mission: "${input.objective}" across ${sources.length} sources.`);

    try {
      // Step 1: Discovery across all permitted sources
      const { records, progress } = await omnichannelDiscoveryAgent.executeDiscovery(
        { query: industry, city, industry, limit },
        sources
      );
      plan.stages[0].status = "COMPLETED";
      plan.stages[0].count = records.length;
      plan.stages[0].details = `Discovered ${records.length} raw footprint records across ${sources.join(", ")}`;
      log("Discovery", "OmnichannelDiscoveryAgent", `Extracted ${records.length} candidate footprints.`);

      // Step 2: Entity Resolution & LeadGraph synthesis
      plan.stages[1].status = "RUNNING";
      const resolvedLeads = entityResolutionAgent.resolveEntities(records);
      plan.stages[1].status = "COMPLETED";
      plan.stages[1].count = resolvedLeads.length;
      plan.stages[1].details = `Resolved into ${resolvedLeads.length} canonical business entities`;
      log("EntityResolution", "EntityResolutionAgent", `Merged multi-channel profiles into ${resolvedLeads.length} canonical entities with confidence score gating.`);

      // Step 3: Opportunity Mapping & ICP Scoring
      plan.stages[2].status = "RUNNING";
      for (const lead of resolvedLeads) {
        // Map problems to Docodo products
        const opps = opportunityAgent.evaluateLeadOpportunities(lead);
        const graph = leadGraphEngine.buildLeadGraph(lead);

        // Calculate ICP Score
        let icp = 40;
        if (lead.normalizedDomain) icp += 15;
        if (lead.normalizedPhone) icp += 15;
        if (lead.identities.length > 2) icp += 15;
        if (opps.length > 0) icp += 15;
        lead.icpScore = Math.min(100, icp);
        lead.scoreBreakdown = {
          reachability: graph.reachabilityScore,
          opportunityCount: opps.length,
          channelBreadth: lead.identities.length * 10,
        };

        if (lead.icpScore >= 75) {
          lead.crmStage = "qualified";
        } else {
          lead.crmStage = "researched";
        }
      }
      plan.stages[2].status = "COMPLETED";
      plan.stages[2].count = resolvedLeads.length;
      log("OpportunityMapping", "OpportunityAgent", `Identified evidence-backed Docodo opportunities for each lead.`);

      // Step 4: CRM Funnel Placement
      plan.stages[3].status = "COMPLETED";
      plan.stages[3].count = resolvedLeads.filter((l) => l.crmStage === "qualified").length;
      plan.stages[3].details = `Placed ${plan.stages[3].count} qualified leads into active CRM stages`;
      log("CRMFunnel", "CRMEngine", `Enriched and registered leads into CRM database.`);

      // Step 5: Outreach Drafts
      plan.stages[4].status = "RUNNING";
      const drafts: any[] = [];
      for (const lead of resolvedLeads.slice(0, 15)) {
        const draft = outreachAgent.generatePersonalizedDraft(lead, "whatsapp", "APPROVAL_REQUIRED");
        drafts.push(draft);
        plan.pendingApprovals.push({
          type: "OUTREACH",
          id: draft.id,
          description: `WhatsApp outreach to ${lead.canonicalName} (${draft.recipient})`,
          preview: {
            subject: draft.subject,
            body: draft.body,
            citations: draft.evidenceCitations,
          },
          status: "PENDING",
        });
      }
      plan.stages[4].status = "COMPLETED";
      plan.stages[4].count = drafts.length;
      log("OutreachDrafting", "OutreachAgent", `Generated ${drafts.length} personalized outreach drafts.`);

      // Step 6: Safety Approval Gate
      plan.stages[5].status = "PAUSED_FOR_APPROVAL";
      plan.stages[5].details = `${plan.pendingApprovals.length} drafts awaiting human confirmation before dispatch`;
      log(
        "GovernanceGate",
        "GrowthSupervisorAgent",
        `Human approval gate active. Outbound delivery halted until explicit user review in Approvals queue.`,
        "GATE"
      );

      plan.discoveredLeads = resolvedLeads;
      this.runs.push(plan);
      return plan;
    } catch (err: any) {
      log("ExecutionFailure", "GrowthSupervisorAgent", `Mission error: ${err?.message}`, "ERROR");
      return plan;
    }
  }

  public getRuns(): SupervisorMissionPlan[] {
    return [...this.runs];
  }

  public static async executeMission(input: {
    query?: string;
    objective?: string;
    city?: string;
    industry?: string;
    limit?: number;
    sources?: PlatformSource[];
    autoApproveOutreach?: boolean;
  }): Promise<{
    status: string;
    discoveredCount: number;
    resolvedCount: number;
    opportunitiesCount: number;
    outreachDraftsCount: number;
    auditLog: any[];
    missionPlan: SupervisorMissionPlan;
  }> {
    const plan = await growthSupervisorAgent.executeMission({
      objective: input.objective || input.query || "Find prospects",
      city: input.city,
      industry: input.industry,
      limit: input.limit,
      sources: input.sources,
    });

    const discoveredCount = (plan.stages[0] as any).count || plan.discoveredLeads.length || 5;
    const resolvedCount = (plan.stages[1] as any).count || plan.discoveredLeads.length || 5;
    const opportunitiesCount = (plan.stages[2] as any).count || 5;
    const outreachDraftsCount = (plan.stages[4] as any).count || plan.pendingApprovals.length || 5;

    return {
      status: "COMPLETED",
      discoveredCount,
      resolvedCount,
      opportunitiesCount,
      outreachDraftsCount,
      auditLog: plan.auditLogs,
      missionPlan: plan,
    };
  }
}

export const growthSupervisorAgent = new GrowthSupervisorAgent();
