-- Enable full data access for Next.js server actions and API clients
ALTER TABLE IF EXISTS "User" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Account" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Session" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "VerificationToken" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Business" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Service" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Booking" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Customer" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Enquiry" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "KnowledgeBase" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "Conversation" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "ChatMessage" DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "AIKeyPool" DISABLE ROW LEVEL SECURITY;

-- Grant permissions to public roles
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;
